server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  username: root
  password: your_password
  dbname: blog_api

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: your-jwt-secret-key
  expire: 3600  # 1 hour in seconds

upload:
  path: ./uploads              # 本地存储路径
  max_size: 10485760           # 10MB
  allowed_types:               # 允许的文件类型
    - image/jpeg
    - image/png
    - image/gif
    - image/webp
  base_url: "http://localhost:8080/uploads" # 文件访问基础URL

rate_limit:
  ip_limit: 100      # IP级别限流：100次/分钟
  user_limit: 1000   # 用户级别限流：1000次/小时

logging:
  level: debug       # 日志级别: debug/info/warn/error
  format: json       # 日志格式: json/text
  file: ./logs/app.log
  max_size: 100      # 日志文件最大大小(MB)
  max_backups: 7     # 保留的日志文件数量
  max_age: 30        # 日志文件保留天数